import type { Route, RoadAlert, BikerSpot } from "@/lib/types";

// Georgia (Europe) — representative coordinates for routes/alerts/spots
// All lat/lng are authentic Georgian locations

export const MOCK_ROUTES: Route[] = [
  {
    id: "r-001",
    name: "Military Highway Panorama",
    description: "The legendary Georgian Military Highway from Tbilisi to Kazbegi. Breathtaking mountain passes, iconic Gergeti Trinity Church views, and switchbacks that demand full concentration.",
    difficulty: "advanced",
    surface: "asphalt_new",
    status: "verified",
    distanceKm: 148,
    durationMin: 210,
    elevationGain: 2385,
    waypoints: [
      { lat: 41.6938, lng: 44.8015 },
      { lat: 42.0, lng: 44.68 },
      { lat: 42.4, lng: 44.5 },
      { lat: 42.659, lng: 44.658 },
    ],
    startPoint: { lat: 41.6938, lng: 44.8015 },
    endPoint:   { lat: 42.659,  lng: 44.658  },
    tags: ["mountain", "panoramic", "switchbacks", "historic"],
    region: "Mtskheta-Mtianeti",
    createdAt: "2024-03-12T10:00:00Z",
    updatedAt: "2024-06-01T08:30:00Z",
    likeCount: 342,
    rideCount: 1240,
  },
  {
    id: "r-002",
    name: "Kakheti Wine Road",
    description: "A smooth, rolling cruise through Georgia's premier wine country. Ancient monasteries, amber wine estates, and welcoming villages make this a perfect weekend loop.",
    difficulty: "beginner",
    surface: "asphalt_old",
    status: "verified",
    distanceKm: 93,
    durationMin: 130,
    elevationGain: 320,
    waypoints: [
      { lat: 41.64, lng: 45.0 },
      { lat: 41.67, lng: 45.36 },
      { lat: 41.82, lng: 45.72 },
    ],
    startPoint: { lat: 41.64, lng: 45.0 },
    endPoint:   { lat: 41.82, lng: 45.72 },
    tags: ["wine", "cultural", "countryside", "easy"],
    region: "Kakheti",
    createdAt: "2024-01-20T09:00:00Z",
    updatedAt: "2024-05-18T12:00:00Z",
    likeCount: 218,
    rideCount: 876,
  },
  {
    id: "r-003",
    name: "Svaneti Alpine Challenge",
    description: "One of the most demanding routes in the Caucasus. Unpredictable gravel sections, river crossings, and jaw-dropping Svan tower villages reward those who attempt it.",
    difficulty: "extreme",
    surface: "gravel",
    status: "verified",
    distanceKm: 214,
    durationMin: 480,
    elevationGain: 4120,
    waypoints: [
      { lat: 42.5, lng: 42.5 },
      { lat: 42.9, lng: 42.9 },
      { lat: 43.1, lng: 42.7 },
    ],
    startPoint: { lat: 42.5, lng: 42.5 },
    endPoint:   { lat: 43.1, lng: 42.7 },
    tags: ["alpine", "gravel", "extreme", "unesco"],
    region: "Samegrelo-Zemo Svaneti",
    createdAt: "2024-02-05T11:00:00Z",
    updatedAt: "2024-06-10T07:45:00Z",
    likeCount: 512,
    rideCount: 389,
  },
  {
    id: "r-004",
    name: "Adjara Coastal Sweep",
    description: "A sublime Black Sea coast ride from Batumi heading north. Fresh asphalt, sea breezes, and subtropical landscape make this Georgia's most relaxing biker route.",
    difficulty: "intermediate",
    surface: "asphalt_new",
    status: "verified",
    distanceKm: 76,
    durationMin: 95,
    elevationGain: 180,
    waypoints: [
      { lat: 41.64, lng: 41.63 },
      { lat: 41.8,  lng: 41.72 },
      { lat: 42.0,  lng: 41.68 },
    ],
    startPoint: { lat: 41.64, lng: 41.63 },
    endPoint:   { lat: 42.0,  lng: 41.68 },
    tags: ["coastal", "sea", "scenic", "new-asphalt"],
    region: "Adjara",
    createdAt: "2024-04-08T14:00:00Z",
    updatedAt: "2024-06-15T09:00:00Z",
    likeCount: 287,
    rideCount: 640,
  },
];

export const MOCK_ALERTS: RoadAlert[] = [
  {
    id: "a-001",
    category: "new_asphalt",
    severity: "low",
    title: "New Asphalt — Gudauri Pass",
    description: "Fresh resurfacing between km 143–158. Excellent grip, some lane markings still being applied.",
    location:   { lat: 42.47, lng: 44.48 },
    radius: 8000,
    reportedAt: new Date(Date.now() - 3 * 3600_000).toISOString(),
    expiresAt:  null,
    upvotes: 47,
    verified: true,
  },
  {
    id: "a-002",
    category: "gravel_hazard",
    severity: "high",
    title: "Gravel Spread — Signagi Road",
    description: "Significant gravel from a landslide debris flow. Approx 200m stretch, right-hand lane. Reduce to under 40 km/h.",
    location:   { lat: 41.62, lng: 45.55 },
    radius: 600,
    reportedAt: new Date(Date.now() - 30 * 60_000).toISOString(),
    expiresAt:  new Date(Date.now() + 48 * 3600_000).toISOString(),
    upvotes: 89,
    verified: true,
  },
  {
    id: "a-003",
    category: "speed_camera",
    severity: "low",
    title: "Speed Camera — Tbilisi Bypass",
    description: "Fixed camera at intersection with N7 highway. 90 km/h limit enforced.",
    location:   { lat: 41.72, lng: 44.91 },
    radius: 200,
    reportedAt: new Date(Date.now() - 7 * 86_400_000).toISOString(),
    expiresAt:  null,
    upvotes: 203,
    verified: true,
  },
  {
    id: "a-004",
    category: "roadworks",
    severity: "medium",
    title: "Bridge Repair — Rioni River",
    description: "Single-lane alternating traffic. Expect 15–25 min delays. Works ongoing Mon–Fri 08:00–18:00.",
    location:   { lat: 42.27, lng: 43.01 },
    radius: 1500,
    reportedAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
    expiresAt:  new Date(Date.now() + 30 * 86_400_000).toISOString(),
    upvotes: 34,
    verified: true,
  },
  {
    id: "a-005",
    category: "biker_cafe",
    severity: "low",
    title: "Riders' Checkpoint Café — Kazbegi",
    description: "Legendary biker meeting point. Khinkali, hot coffee, and a fire pit. Open 24/7 in season.",
    location:   { lat: 42.66, lng: 44.65 },
    radius: 100,
    reportedAt: new Date(Date.now() - 60 * 86_400_000).toISOString(),
    expiresAt:  null,
    upvotes: 312,
    verified: true,
  },
  {
    id: "a-006",
    category: "fuel_station",
    severity: "low",
    title: "Last Fuel Before Svaneti",
    description: "Final reliable fuel station before entering upper Svaneti valley. Fill up here.",
    location:   { lat: 42.51, lng: 42.77 },
    radius: 100,
    reportedAt: new Date(Date.now() - 90 * 86_400_000).toISOString(),
    expiresAt:  null,
    upvotes: 156,
    verified: true,
  },
];

export const MOCK_SPOTS: BikerSpot[] = [
  {
    id: "s-001",
    name: "Iron Horse Tbilisi",
    category: "cafe",
    description: "Tbilisi's premier motorcycle café. Custom bikes on display, local craft beer, and the city's best community bulletin board for routes.",
    location:   { lat: 41.693, lng: 44.806 },
    address:    "12 Kostava St, Tbilisi",
    phone:      "+995 32 292 0000",
    website:    "https://example.ge/ironhorse",
    openHours:  "09:00 – 23:00",
    rating:     4.8,
    reviewCount: 234,
    amenities:  ["wifi", "parking", "tools", "beer"],
    verified:   true,
  },
  {
    id: "s-002",
    name: "Summit View Rest — Gudauri",
    category: "rest_area",
    description: "Designated rest area at 2200m elevation with panoramic Greater Caucasus views. Covered seating, toilet facilities.",
    location:   { lat: 42.48, lng: 44.5 },
    address:    "Georgian Military Highway, km 151",
    phone:      null,
    website:    null,
    openHours:  "Open 24h",
    rating:     4.6,
    reviewCount: 89,
    amenities:  ["toilets", "covered-seating", "water"],
    verified:   true,
  },
  {
    id: "s-003",
    name: "Batumi Riders Hub",
    category: "cafe",
    description: "Black Sea beachfront biker stop. Incredible sunset views, local Adjarian cuisine, and a weekly Friday ride meetup.",
    location:   { lat: 41.646, lng: 41.636 },
    address:    "8 Ninoshvili St, Batumi",
    phone:      "+995 422 27 0000",
    website:    null,
    openHours:  "10:00 – 02:00",
    rating:     4.7,
    reviewCount: 167,
    amenities:  ["wifi", "parking", "food", "beer"],
    verified:   true,
  },
];
